export {default as Avatar} from './Avatar'
export {default as Icon} from './Icon'
export {default as Button} from './Button'
export {default as Badge} from './Badge'
export {default as Checkbox} from './Checkbox'
export {default as Input} from './Input'
export {default as InputNumber} from './InputNumber'
export {default as Tag} from './Tag'
